CREATE TABLE roles (  
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,  
  role varchar(20) NOT NULL UNIQUE,  
  PRIMARY KEY (id)  
) 
  
CREATE TABLE users (  
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,  
  login varchar(20) NOT NULL UNIQUE,  
  password varchar(20) NOT NULL,
  enabled int NOT NULL,
  email varchar(20) NOT NULL,
  firstname varchar(20) NOT NULL,
  lastname varchar(40) NOT NULL,
  city varchar(20) NOT NULL,
  street varchar(60) NOT NULL,
  zipcode varchar(6) NOT NULL,
  birthdate date,
  PRIMARY KEY (id)  
) 
  
CREATE TABLE user_roles (  
  user_id int NOT NULL,  
  role_id int NOT NULL,  
  FOREIGN KEY (user_id) REFERENCES users(id),  
  FOREIGN KEY (role_id) REFERENCES roles(id)  
) 

INSERT INTO USERS (LOGIN, PASSWORD, ENABLED, FIRSTNAME, EMAIL, LASTNAME, CITY, STREET, ZIPCODE, BIRTHDATE) VALUES ('admin', 'admin', 1, '', '', '', '', '', '', '2001-01-01')
INSERT INTO ROLES (ROLE) VALUES ('ADMIN')
INSERT INTO ROLES (ROLE) VALUES ('MODERATOR')
INSERT INTO ROLES (ROLE) VALUES ('USER')

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1,1)

